fix(scripts): call API to fetch bottle URL and hash
Using bottle info call does not return all systems, and passing --variations causes:

Error: Invalid usage: Cannot call #to_hash_with_variations on formulae loaded from the internal API

Signed-off-by: Jakub Sokołowski <jakub@status.im>